# Generated by Django 2.1.3 on 2018-11-28 17:48

from django.db import migrations, models
import website.utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True)),
                ('organizer', models.CharField(blank=True, max_length=255, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('whole_day_event', models.BooleanField(default=False)),
                ('venue', models.TextField()),
                ('enabled', models.BooleanField(default=True)),
                ('description_pre', models.TextField(blank=True, help_text='Pre-event description; like invitations, how to reach there, etc.', null=True)),
                ('description_post', models.TextField(blank=True, help_text='Post event description; like thanking the attendees.', null=True)),
                ('description_common', models.TextField(blank=True, help_text="Description to show when pre and post aren'nt available.", null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('location', website.utils.fields.LocationField(blank=True, max_length=255)),
                ('featured', models.BooleanField(default=True)),
            ],
        ),
    ]
